### PR TITLE
Match all_of() implementation to any_of()

### LINKED ISSUE #269: Out of context `all_of()` should error
```r
tidyselect::all_of("x")
#> [1] "x"

tidyselect::any_of("x")
#> Error:
#> ! `any_of()` must be used within a *selecting* function.
#> ℹ See <https://tidyselect.r-lib.org/reference/faq-selection-context.html>.
```

### PR DESCRIPTION
**Pull request by hadley**
Fixes #269

### CODE REVIEW

**Comment by hadley** [comment]
@lionel- any idea why R-devel generates a different parent error?

**Comment by hadley** [comment]
One simple way to fix the issue is to remove the error changing in `eval_context()`. I think that mildly improves the error in the common case of a helper erroring on bad input, at the cost of mildly worsening the error if the user supplies a non-helper that errors.

File: tests/testthat/test-helpers-vector.R [hunk 1]
```diff
@@ -51,10 +38,21 @@ test_that("any_of() is lax", {
 })
 
 test_that("all_of() and any_of() check their inputs", {
-  expect_error(select_loc(letters2, all_of(NA)), "missing")
-  expect_error(select_loc(letters2, any_of(NA)), "missing")
-  expect_error(select_loc(letters2, all_of(na_chr)), "missing")
-  expect_error(select_loc(letters2, any_of(na_chr)), "missing")
-  expect_error(select_loc(letters2, all_of(TRUE)), class = "vctrs_error_subscript_type")
-  expect_error(select_loc(letters2, any_of(TRUE)), class = "vctrs_error_subscript_type")
+  expect_snapshot(error = TRUE, {
```
Comment (lionel-) [inline tests/testthat/test-helpers-vector.R:41]: Could you use `expect_error()` within `expect_snapshot()` to avoid weakening these tests until r-lib/testthat#1667 is solved please?

**Review by lionel- — APPROVED** [review]
IIUC you need to install rlang 1.0.4 locally and make tidyselect depend on it so that version is installed on CI. Then the snapshots should be consistent across platforms.

**Comment by hadley** [comment]
Still seeing the failure.

**Comment by lionel-** [comment]
@hadley I'll have to take a deeper look. My local install behaves like r-devel on CI :/

File: tests/testthat/_snaps/eval-select.md [hunk 2]
```diff
@@ -4,8 +4,7 @@
       (expect_error(select_loc(mtcars, f())))
     Output
       <error/rlang_error>
-      Error in `select_loc()`:
-      Caused by error in `f()`:
+      Error in `f()`:
```
Comment (lionel-) [inline tests/testthat/_snaps/eval-select.md:7]: Can we keep the chained error here? Chained error support is one the main feature of this release so I'd like to keep them.
